# Tarteb Supabase local config
# See https://supabase.com/docs/guides/cli/config

project_id = "tarteb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[auth]
enabled = true
site_url = "io.supabase.tarteb://login-callback/"
additional_redirect_urls = []

[auth.sms]
enable_signup = true
enable_confirmations = true

[storage]
enabled = true
file_size_limit = "5MB"
